[workspace]

members = [
    "hst-cdx",
    "hst-cli",
    "hst-deactivations",
    "hst-memory-lol",
    "hst-reports",
    "hst-tools",
    "hst-tw-db",
    "hst-tw-images",
    "hst-tw-profiles",
    "hst-tw-utils"
]
