[workspace]

members = [
    "hst-cli",
    "hst-deactivations",
    "hst-tools",
    "hst-tw-db",
    "hst-tw-follow",
    "hst-tw-images",
    "hst-tw-profiles",
    "hst-tw-profiles-dir",
    "hst-tw-profiles-s3",
    "hst-tw-utils",
    "hst-utils"
]
